CREATE TABLE PACIENTES (
  COD_PACIENTE VARCHAR(15)  NOT NULL PRIMARY KEY
  COMMENT 'Identificador único del paciente con formato COD_NNNNNNNNNN',
  NOMBRE       VARCHAR(128) NOT NULL
  COMMENT 'Nombre del Paciente',
  APELLIDO_1   VARCHAR(255) NOT NULL
  COMMENT 'Primer Apellido del Paciente',
  APELLIDO_2   VARCHAR(255) NULL
  COMMENT 'Segundo Apellido del Paciente'
);

CREATE TABLE MEDICOS_REMITENTES (
  COD_MEDICO VARCHAR(15)  NOT NULL PRIMARY KEY
  COMMENT 'Identificador unico del medico remitente con formato COD_NNNNNNNNN',
  NOMBRE     VARCHAR(128) NOT NULL
  COMMENT 'Nombre del Medico Remitente',
  APELLIDO_1 VARCHAR(255) NOT NULL
  COMMENT 'Nombre del Medico Remitente',
  APELLIDO_2 VARCHAR(255) NULL
  COMMENT 'Segundo Apellido del Medico Remitente',
  NIF        VARCHAR(10)  NOT NULL
  COMMENT 'NIF del Medico Remitente'
);

CREATE TABLE MEDICOS_AP (
  COD_MEDICO VARCHAR(15)  NOT NULL PRIMARY KEY
  COMMENT 'Identificador único del Medico de AP con formato COD_NNNNNNNNNN',
  NOMBRE     VARCHAR(128) NOT NULL
  COMMENT 'Nombre del Medico de AP',
  APELLIDO_1 VARCHAR(255) NOT NULL
  COMMENT 'Primer Apellido del de AP',
  APELLIDO_2 VARCHAR(255) NULL
  COMMENT 'Segundo Apellido del de AP',
  NIF        VARCHAR(10)  NOT NULL
  COMMENT 'NIF del Medico de AP'
);

CREATE TABLE CLINICA_REMITENTE (
  COD_CLINICA VARCHAR(15)  NOT NULL PRIMARY KEY
  COMMENT 'Identificador único de la clinica remitente con formato COD_NNNNNNNNNN',
  NOMBRE      VARCHAR(128) NOT NULL
  COMMENT 'Nombre de la clínica remitente',
  DESCRIPCION VARCHAR(255) NULL
  COMMENT 'Detalles de la clinica remitente'
);

CREATE TABLE CLINICA_AP (
  COD_CLINICA VARCHAR(15)  NOT NULL PRIMARY KEY
  COMMENT 'Identificador único de la clinica de AP con formato COD_NNNNNNNNNN',
  NOMBRE      VARCHAR(128) NOT NULL
  COMMENT 'Nombre de la clínica de AP',
  DESCRIPCION VARCHAR(255) NULL
  COMMENT 'Detalles de la clinica de AP'
);

CREATE TABLE ANALISIS_AP (
  COD_ANALISIS      VARCHAR(15) NOT NULL
  COMMENT 'Identificador unico del analisis clinico',
  FECHA_REGISTRO    DATETIME    NOT NULL
  COMMENT 'Fecha en que se creo el analisis',
  COD_PACIENTE      VARCHAR(15) NOT NULL
  COMMENT 'Identificador del Paciente analizado',
  MEDICO_REMITENTE  VARCHAR(15) NOT NULL
  COMMENT 'Identificador del Medico que solicito el analisis',
  CLINICA_REMITENTE VARCHAR(15) NOT NULL
  COMMENT 'Identificador de la clinica que solicito el analisis',
  MEDICO_AP         VARCHAR(15) NOT NULL
  COMMENT 'Identificador del Medico que realizo el analisis',
  CLINICA_AP        VARCHAR(15) NOT NULL
  COMMENT 'Identificador de la clinica que realizo el analisis',
  PRIMARY KEY (COD_ANALISIS),
  KEY FK_ANALISIS_PACIENTE_idx (COD_PACIENTE),
  KEY FK_ANALISIS_MEDICO_REMITENTE_idx (MEDICO_REMITENTE),
  KEY FK_ANALISIS_CLINICA_REMITENTE_idx (CLINICA_REMITENTE),
  KEY FK_ANALISIS_MEDICO_AP_idx (MEDICO_AP),
  KEY FK_ANALISIS_CLINICA_AP_idx (CLINICA_AP),
  CONSTRAINT FK_ANALISIS_CLINICA_AP FOREIGN KEY (CLINICA_AP) REFERENCES CLINICAS_AP (COD_CLINICA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ANALISIS_CLINICA_REMITENTE FOREIGN KEY (CLINICA_REMITENTE) REFERENCES CLINICAS_REMITENTES (COD_CLINICA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ANALISIS_MEDICO_AP FOREIGN KEY (MEDICO_AP) REFERENCES MEDICOS_AP (COD_MEDICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ANALISIS_MEDICO_REMITENTE FOREIGN KEY (MEDICO_REMITENTE) REFERENCES MEDICOS_REMITENTES (COD_MEDICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ANALISIS_PACIENTE FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTES (COD_PACIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
